version: '3.8'

volumes:
  redis_data: {}

networks:
  import-api:
    driver: bridge

services:

  import-api:
    container_name: import-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./:/usr/import-api/app
    entrypoint: sh -c "npm install && npm run start:dev"
    networks:
      - import-api

  redis:
    image: redis
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    entrypoint: redis-server --appendonly yes
    networks:
      - import-api