version: '3.8'

volumes:
  redis_data: {}

networks:
  import-api:
    driver: bridge

services:
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    entrypoint: redis-server --appendonly yes
    networks:
      - import-api